src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>test__c</fullName>
        <label>test</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Point_Audit__c.object
<CustomObject>
    <label>Point Audit</label>
    <nameField>
        <displayFormat>PA-{000}</displayFormat>
        <label>Point Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test__mdt.object
<CustomObject>
    <label>Test</label>
    <pluralLabel>Test</pluralLabel>
</CustomObject>

classes/Auto_Test.cls
Public class Auto_Test{
    
    Public Point_Audit__c point;
    Public Test__mdt t1;
    Public Account accpoint;
    Public Auto_Test(ApexPages.StandardController controller){
        point=new Point_Audit__c();
    }
    public Point_Audit__c getpoint(){
        return point;
    }

    Public PageReference NewPoint(){
    accpoint.test__c='test';
    PageReference pdf = Page.Auto_Test;
        insert point;
         PageReference ref = new PageReference('https://cs5.salesforce.com/a02/o');
        ref.setRedirect(true);
        return ref;
    }
}